// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqcpckohybdsowudeaoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY3Bja29oeWJkc293dWRlYW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzQyNzQsImV4cCI6MjA2NzY1MDI3NH0.0KxdvjA5_trTALf0avio8EfROxlhxp1_Ox94cxcO3Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});